---

- name: Tasks that will run on each raspberry pi after being ansible-pull'd
  hosts: 127.0.0.1
  connection: local

  vars:
    git_repo: ssh://....git
    working_dir: /var/wiloc
    logging_dir: {{working_dir}}/log

    server_endpoint: http://api.josephshearer.net/wiloc/api/v1

    user: root
    daemon: {{working_dir}}/sniffing/sniffer_launch.py
    pidfile: /var/run/{{service_name}}.pid
    daemon_opts: "--endpoint {{server_endpoint}} --mode dumpcap --pidfile {{pidfile}} --logfile {{logging_dir}}"
    service_name: sniffer

  tasks:

    - name: Ensure working directory exists.
      file: path={{working_dir}} state=directory

    - name: Ensure logging directory works.
      file: path={{logging_dir}} state=directory
    
    - name: Clone the git repo for 
      git: repo={{git_repo}} accept_hostkey=yes dest={{working_dir}}
      register: git_pull

    - name: Set up wifi correctly
      command: /usr/bin/python2 -m WiLoc.infrastructure.setup_wifi chdir={{working_dir}}
      when: git_pull.changed
      tags: update

    - name: Stop the sniffing service
      service: name={{service_name}}.service state=stopped enabled=no
      when: git_pull.changed
      tags: update

    - name: Add daemon script
      template: src=ansible/templates/systemd-template.j2 dest=/etc/systemd/system/multi-user.target.wants/{{service_name}}.service mode=777
      when: git_pull.changed
      tags: update

    - name: Ensure the daemon is started
      service: name={{service_name}}.service state=started enabled=yes
      when: git_pull.changed
      tags: update